# Web Server Deployment Configuration Port
server.port=8080

# Relational In-Memory H2 Engine Database Interconnection Properties
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate Core Object-Relational Mapping Framework Strategy Drivers
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Developer In-Browser Graphic Terminal System Interconnection Console
spring.h2.console.enabled=true
